project name stays in text field when you go back
patrickbrett/mlvet pull request #166
Opened 2022-08-05 02:36 UTC by emmapainter

Elevated the state so that the project name can remain filled when the user continues to the next modal then navigates back to the new project view

## Summary

Lifted the project name state from the new project view into the modal container so that the project name persists when you continue to the import media view then navigate back again.

<hr/>

Currently the project name clears when the user navigates back to the project name view, which would be annoying if they only wanted to fix a simple typo.

<hr/>

### OS

- [ ] Linux
- [x] MacOS
- [ ] Windows

2022-08-05 05:28 UTC, hhen0005 approved these changes

2022-08-05 14:16 UTC, exquisitebin commented
I'm currently working on Issue #101, in which the idea is that the user is prompted with a dialog asking if they want to abandon the new project when they click outside of the Modal. Where they can choose to continue and not close the Modal, or close the Modal and start a new project again.

Not sure if remembering the previous project name clashes with this idea. Happy to hear thoughts on this.

2022-08-05 14:21 UTC, exquisitebin requested changes
I'm currently working on Issue https://github.com/chloebrett/mlvet/issues/101 in branch [bugfix/click-outside-of-modal](https://github.com/chloebrett/mlvet/tree/bugfix/click-outside-of-modal). The idea is that the user is prompted with a dialog asking if they want to abandon the new project when they click outside of the Modal. Where they can choose to continue and not close the Modal, or close the Modal and start a new project again.

Not sure if remembering the previous project name clashes with this idea. Happy to hear thoughts on this.

2022-08-06 04:11 UTC, Taz17 commented
@exquisitebin If you will be showing a dialog and the user confirms they want to exit then you should use the `setProjectName` hook to re-set the `projectName` back to an empty string.

This PR has more to do with how the app behaves when you go back a step in the existing modal rather than what happens when you click off

2022-08-06 04:13 UTC, Taz17 approved these changes

2022-08-06 04:30 UTC, exquisitebin requested changes
Mutaz clarified my query, and I agree it doesn't clash with the issue I'm working on.

I just have a bug that when you press back to name the new project the continue button is disabled until you change the text (which ideally you wouldn't have to).

![image](https://user-images.githubusercontent.com/58348527/183233806-417ab00a-0c34-4ccb-b483-e17d0662f7f0.png)

2022-08-06 07:12 UTC, fwang1703 approved these changes
Nice!

2022-08-09 07:44 UTC, emmapainter commented
> Mutaz clarified my query, and I agree it doesn't clash with the issue I'm working on.
> 
> I just have a bug that when you press back to name the new project the continue button is disabled until you change the text (which ideally you wouldn't have to).
> 
> ![image](https://user-images.githubusercontent.com/58348527/183233806-417ab00a-0c34-4ccb-b483-e17d0662f7f0.png)

@exquisitebin this should be fixed now

2022-08-09 10:00 UTC, exquisitebin approved these changes
Looks good, awesome!

2022-08-09 12:04 UTC, rileykeane commented on src/renderer/components/NewProjectModal/NewProjectView.tsx
> +      disabled={!projectName.trim()}
👀

2022-08-11 01:58 UTC, merged