Feature/edit marker
patrickbrett/mlvet pull request #187
Opened 2022-08-17 02:22 UTC by fwang1703

## Summary

This PR is adding an EditMarker component which is rendered when a word is deleted in the transcription. This is so that users will know where original transcription has been deleted or moved.

### Why is this change needed?

This change is needed to implement the feature which allows users to restore text when it has been deleted. The marker acts as a visual aid to users to know where text has been deleted/moved. 

### What did you change?

- Created the `EditMarker` component
- Added logic to the `TranscriptionBlock` to determine when to render an EditMarker

### Screenshots of UI changes, if any

https://user-images.githubusercontent.com/40136329/185019784-df9b174e-5d02-4f3d-9dc8-1022e959fbe6.mov

Steps take in video
- Delete a word and see EditMarker
- Delete words before and after the current EditMarker (they will combine into 1 EditMarker)
- Show EditMarkers in different spots of the transcription (as long as there is 1 word in between deleted words)
- Copying a word somewhere else and deleting it. Does not show EditMarker as it is not the original spot
- Show that EditMarker does not disappear if transcription is edited
- EditMarker disappears if original word returned to its place (via copy and pasting)

### Design Docs

https://www.figma.com/file/vPh49OC7hJpMD7cQMAnBUo/UI-Design?node-id=1034%3A2147 

### OS

- [ ] Linux
- [x] MacOS
- [ ] Windows

2022-08-18 07:14 UTC, emmapainter approved these changes

2022-08-19 01:16 UTC, chloebrett requested changes
Looks pretty good, just a few stylistic suggestions and one bug fix.

There is also another bug. To replicate:
- Delete one word
- Cut a range from the word before it to the word after it (including the delete marker)
- This will leave the delete marker there
- Then paste to another place in the text
- This will create a second delete marker

When this happens, you end up with two delete markers - the preferred behaviour is that the one in the original location should be there, but the one in the pasted text shouldn't be.

I'm happy for this PR to be merged without that bug being fixed, as I think it will take a lot more thinking and some changes to the way cut/paste/delete work. (i.e. not pasting deleted words, marking words as deleted when cut instead of actually removing them, and maybe some other changes)

2022-08-19 01:16 UTC, chloebrett commented on src/renderer/components/EditMarker.tsx
> +    <svg
Nice 🌟

2022-08-19 01:16 UTC, chloebrett commented on src/renderer/components/TranscriptionBlock.tsx
> +import { Transcription, Word as WordType } from 'sharedTypes';
I like the idea of differentiating between the `Word` react component and the `Word` type/interface - maybe we should do this more generally, rather than in this file, because I can foresee this being an issue for other changes as well. Perhaps the easiest way would be to rename the react component to be something like `WordComponent` instead though, as there will be fewer places to update. What do you think?

2022-08-19 01:16 UTC, chloebrett commented on src/renderer/components/TranscriptionBlock.tsx
> +  const renderEditMarker = (
I think this is probably a good candidate for its own react component, to avoid cluttering up the TranscriptionBlock file. Thoughts?

2022-08-19 01:16 UTC, chloebrett commented on src/renderer/components/TranscriptionBlock.tsx
> +    const hasNoNeighbourMarker =
There is a small bug here - to replicate:

- delete the first word
- delete the second word

This creates no marker, but it should create one marker.

2022-08-19 01:30 UTC, rileykeane requested changes
Looks good, just a few little things in addition to Chloe's comments. 

- It would be nice if the edit marker was bottom aligned with the word
<img width="552" alt="Screen Shot 2022-08-19 at 11 27 59 AM" src="https://user-images.githubusercontent.com/27614346/185522781-c5dd233d-4220-4588-99f3-863893d3e242.png">

- The edit markers will need a key since we can have multiple rendered simultaneously. React is currently throwing an warning about this.

2022-08-22 04:32 UTC, fwang1703 commented on src/renderer/components/TranscriptionBlock.tsx
> +import { Transcription, Word as WordType } from 'sharedTypes';
Updated! React component has been refactored to `WordComponent`

2022-08-22 04:32 UTC, fwang1703 commented on src/renderer/components/TranscriptionBlock.tsx
> +  const renderEditMarker = (
Moved to EditMarker react component file

2022-08-22 04:33 UTC, fwang1703 commented on src/renderer/components/TranscriptionBlock.tsx
> +    const hasNoNeighbourMarker =
Did a fix - seems to fix this issue but haven't tested thoroughly enough to know if it has created any other bugs

2022-08-22 04:35 UTC, fwang1703 commented
@rileykeane Is this alignment better?
<img width="101" alt="Screen Shot 2022-08-22 at 1 56 48 pm" src="https://user-images.githubusercontent.com/40136329/185840329-f652df73-c95d-4f7d-94a3-3996fd87a932.png">

2022-08-22 06:18 UTC, chloebrett approved these changes
Looks good aside from the one comment I left

2022-08-22 06:18 UTC, chloebrett commented on src/renderer/components/Editor/EditMarker.tsx
> +  transcription: Transcription;
I believe passing this as a prop means that if the transcription changes at all, every single edit marker will re-render.

Perhaps instead pass `prevWord: Word | null` and `nextWord: Word | null` - that way, they will only re-render when relevant changes happen.

2022-08-23 02:46 UTC, rileykeane approved these changes

2022-08-23 02:54 UTC, merged