Feature/keyboard shortcuts modal
patrickbrett/mlvet pull request #211
Opened 2022-08-25 07:37 UTC by fwang1703

## Summary

Creating a keyboard shortcuts modal. This can be accessed via the menu bar.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/40136329/186603921-3bc11a7f-ed70-4f21-a591-a67f2e892a7d.png">

### Why is this change needed?

Provides all the keyboard shortcut information, which will be useful for the live demo. 

### What did you change?

* New shortcuts dialog created `KeyboardShortcutsDialog`
* Added an IPC receiver to call the modal from the backend 

### Screenshots of UI changes, if any

https://user-images.githubusercontent.com/40136329/186603850-40e0fb01-a155-4023-8e47-f76ee68baf97.mov

### Links to any design documents which you made/used in order to make the decisions that you made.

https://www.figma.com/file/vPh49OC7hJpMD7cQMAnBUo/MLVET-UI-Design?node-id=1355%3A3448

### OS

- [ ] Linux
- [x] MacOS
- [ ] Windows

I need to also have this tested in Windows and Linux too!

2022-08-25 07:41 UTC, chloebrett commented
Can you make it show the correct shortcut _based on_ OS, rather than both? Can use `osQuery` handler to retrieve this - Windows and Linux both use ctrl, Mac uses cmd

2022-08-25 07:53 UTC, chloebrett requested changes
Looks pretty good just a few comments. UI is nice!!

2022-08-25 07:53 UTC, chloebrett commented on src/renderer/pages/Home.tsx
> +  const hasOpenedShortcuts = useSelector(
Rather than duplicating this logic per page, why not bring it up a level (not sure where exactly, probably App.tsx?)

If you do this be aware the redux consumer must be a separate component from the one that contains the store provider.

2022-08-25 07:53 UTC, chloebrett commented on src/main/menu.ts
> +            shell.openExternal('https://electronjs.org');
Maybe remove the links to electron stuff (I know not strictly related to your PR)

2022-08-25 07:53 UTC, chloebrett commented on src/main/menu.ts
> +          {
If you just make the subMenuHelp thing a regular `MenuItemConstructorOptions`, then you can use that here instead, and save on duplication

2022-08-25 07:53 UTC, chloebrett commented on src/renderer/components/KeyboardShortcutsDialog.tsx
> +              'Ctrl + X/⌘ + X',
If you split the shortcuts based on OS you could just do it as something like (pseudocode below)

`const CTRL_OR_CMD = isMacOs ? '⌘' : 'Ctrl';`

Then just interpolate strings like \`${CTRL_OR_CMD} + X\`

2022-08-25 08:29 UTC, Irmy approved these changes
Absolute king - thanks so much for picking this up. Only thing - are we able to get rid of the white rounding on the corners of the modal?  Or change it to a deeper grey?

2022-08-27 01:20 UTC, fwang1703 commented on src/renderer/pages/Home.tsx
> +  const hasOpenedShortcuts = useSelector(
I've chucked the dialog into `AppContents` in App.tsx, hope this is okay

2022-08-27 01:21 UTC, fwang1703 commented on src/main/menu.ts
> +          {
Good pickup don't know why I didn't do this! Updated now

2022-08-27 01:21 UTC, fwang1703 commented on src/renderer/components/KeyboardShortcutsDialog.tsx
> +              'Ctrl + X/⌘ + X',
Updated! Thank you!!

2022-08-27 02:34 UTC, chloebrett approved these changes
I’m going to approve since the suggestions are really minor - looks great!

2022-08-27 02:34 UTC, chloebrett commented on src/renderer/navigation/openShortcuts.tsx
> +const openShortcuts: () => any = async () => {
Return void not any

2022-08-27 02:34 UTC, chloebrett commented on src/renderer/components/KeyboardShortcutsDialog.tsx
> +  const [currentOs, setCurrentOs] = useState<OperatingSystems | null>(null);
OS is not something that ever changes, so I’d almost be tempted to say make this a global var that loads outside the react context - this is fine for now though

2022-08-27 02:34 UTC, chloebrett commented on src/renderer/components/KeyboardShortcutsDialog.tsx
> +        {shortcutsRight.map((shortcut: string) => (
There’s a bit of repetition of the rendering here - e.g. the two word lists render exactly the same as each other, and so do the shortcut lists. Plus there are only very minor differences between the word and shortcut list rendering. Can you try to abstract it a little - should be pretty quick and easy. Apologies for not catching this before

2022-08-27 03:57 UTC, hhen0005 approved these changes
Love it

2022-08-27 04:35 UTC, merged