Transcription page UI cleanup
patrickbrett/mlvet pull request #311
Opened 2022-09-25 10:26 UTC by chloebrett

Separates words into paragraphs; adds project name heading

Screenshot:

<img width="1728" alt="Screen Shot 2022-09-25 at 8 22 11 pm" src="https://user-images.githubusercontent.com/6735055/192138859-ae83fc9e-c4cd-4bc6-a944-48d8e1d794d2.png">

2022-09-25 10:32 UTC, chloebrett commented
Tests failing due to entirely unrelated ffmpeg issue

2022-09-26 03:00 UTC, Irmy requested changes
UI looks so good and the line breaks separate it so well! Can we please get the paragraph threshold to be increased to 4.0 seconds so that Zac can test it and give feedback. I at first suggested 2.0s but then he requested 4.0 or 5.0s.

2022-09-26 05:21 UTC, Mhudlark commented on src/sharedTypes.ts
> +  others: Record<ClientId, IndexRange>;
The tests look like they're failing because `ClientId` is not defined. What is the ffmpeg issue?

2022-09-26 07:56 UTC, chloebrett commented on src/sharedTypes.ts
> +  others: Record<ClientId, IndexRange>;
I’ll take another look

2022-09-27 22:55 UTC, chloebrett commented
@Irmy changed it to 4 seconds

2022-09-27 22:56 UTC, chloebrett commented
FFMPEG error, only seems to be an issue locally not in CI:

```
 FAIL  src/main/export/__tests__/constructEDL.test.ts
  ● Test suite failed to run

    The name `ffmpeg-static` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/Users/chloe/c/mlvet/release/build/mac-arm64/MLVET.app/Contents/Resources/ffmpeg-static/package.json` (package)
      * `/Users/chloe/c/mlvet/release/build/mac/MLVET.app/Contents/Resources/ffmpeg-static/package.json` (package)

    > 1 | import ffmpegStaticPath from 'ffmpeg-static';
        | ^
      2 | import ffprobeStatic from 'ffprobe-static';
      3 | import path from 'path';
      4 |

      at ModuleMap._assertNoDuplicates (node_modules/jest-haste-map/build/ModuleMap.js:230:11)
      at Object.<anonymous> (src/main/ffUtils.ts:1:1)
```

2022-09-27 22:56 UTC, chloebrett commented
FFMPEG error, only seems to be an issue locally not in CI:

```
 FAIL  src/main/export/__tests__/constructEDL.test.ts
  ● Test suite failed to run

    The name `ffmpeg-static` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/Users/chloe/c/mlvet/release/build/mac-arm64/MLVET.app/Contents/Resources/ffmpeg-static/package.json` (package)
      * `/Users/chloe/c/mlvet/release/build/mac/MLVET.app/Contents/Resources/ffmpeg-static/package.json` (package)

    > 1 | import ffmpegStaticPath from 'ffmpeg-static';
        | ^
      2 | import ffprobeStatic from 'ffprobe-static';
      3 | import path from 'path';
      4 |

      at ModuleMap._assertNoDuplicates (node_modules/jest-haste-map/build/ModuleMap.js:230:11)
      at Object.<anonymous> (src/main/ffUtils.ts:1:1)
```

2022-09-27 22:56 UTC, chloebrett commented
Ready to land

2022-09-28 00:08 UTC, Irmy approved these changes

2022-09-28 00:23 UTC, Mhudlark approved these changes
Nice work!

2022-09-28 00:37 UTC, merged